<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="Images/marriage.jpg">
  <title>AboutUs</title>
  <link rel="stylesheet" href="CSS/Main.css">
  <link rel="stylesheet" href="CSS/Header.css">
  <link rel="stylesheet" href="CSS/AboutUs.css">
</head>

<body>
<?php
include("header.php");

?>
  <section style="margin: 50px;" class="AboutUs">
    <div class="container">
      <div class="AboutHaile">
        <div class="photo-div">
        <img class="image-container"
              src="Photos/about.jpg" alt="About Us">
        </div>
        <div class="about-us-text">
          <h2>About Us</h2>
          <p class="text-1">At the Ethiopian Vital Event Registration Agency, our mission is to provide accurate, timely, and secure registration of all vital events, including births, deaths, marriages, Adoption and divorces. 
            Our goal is to ensure that every citizen's life events are officially documented, providing a foundation for legal identity, social services, and public health data. 
            it is a cornerstone of effective governance and public health in Ethiopia.
            and it promotes efficient government planning, effective use of resources and aid, 
            and more accurate monitoring of progress towards achieving the Sustainable Development Goals.
            

            
          </p>
          <div class="watch-video">
            <img src="Images/video-camera.png" alt="VIDEO">
            <a href="Videos/VEDIO3.mp4" target="_blank">
              <p class="text-2">WATCH VIDEO 1&#8594;</p>
            </a>
          </div>
          <div class="watch-video">
            <img src="Images/video-camera.png" alt="VIDEO">
            <a href="Videos/VEDIO2.mp4" target="_blank">
              <p class="text-2" >WATCH VIDEO 2&#8594;</p>
            </a>
          </div>
          <div class="watch-video" >
            <img src="Images/video-camera.png" alt="VIDEO">
            <a href="Videos/VIDEO1.mp4" target="_blank">
              <p class="text-2">WATCH VIDEO 3&#8594;</p>
            </a>
          </div>
        </div>
      </div>
    </div>
    
  </section>

 

  <script src="Script/Index.js"></script>

</body>

</html>